#!/bin/sh

# Tweak glade files to not give warnings with gtk-2.4

find -name "*.glade" | xargs sed -i \
'
/name="focus_on_map"/d
/name="ellipsize"/d
/name="width_chars"/d
/name="single_line_mode"/d
/name="urgency_hint"/d
/name="pack_direction"/d
/name="child_pack_direction"/d
/name="angle"/d
'
