#!/usr/bin/env python2
import sys, os, subprocess
import sqlite3

HASH_CMD = None
DEBUG = False

def hash_file(path):
    cmd_output = subprocess.check_output([HASH_CMD, path]).decode("utf-8")
    hash = cmd_output.split(' ')[0]
    return hash








if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Error, provide the <database path>, <hashing command> and <files list with \\0> ")

    db_path = sys.argv[1]
    HASH_CMD = sys.argv[2]
    files_list = sys.argv[3:]
    files_hashes = dict()

    if not os.path.exists(db_path):
        directory = os.path.dirname(db_path)
        print(directory)
        if not os.path.exists(directory):
            os.makedirs(directory)
        db = sqlite3.connect(db_path)
        cursor = db.cursor()
        cursor.execute(''' CREATE TABLE files(id INTEGER PRIMARY KEY, path TEXT, ctime VARCHAR(50), mtime VARCHAR(50), hash TEXT )  ''')
        db.commit()
    else:
        db = sqlite3.connect(db_path)
        cursor = db.cursor()


    for file_path in files_list:
        cursor.execute('''SELECT * FROM files WHERE path=?''', (file_path,))
        file_record = cursor.fetchone()
        if file_record is not None and len(file_record) > 0:
            if str(os.path.getctime(file_path)) == file_record[2] and str(os.path.getmtime(file_path)) == file_record[3]:
                if DEBUG: print("Found")
                files_hashes[file_path] = file_record[4]
            else:
                if DEBUG: print("Update")
                hash = hash_file(file_path)
                cursor.execute('''UPDATE files SET ctime=?, mtime=?, hash=? WHERE path=?''',
                               (str(os.path.getctime(file_path)), str(os.path.getmtime(file_path)), hash, file_path))
                db.commit()
                files_hashes[file_path] = hash
        else:
            if DEBUG: print("Insert")
            hash = hash_file(file_path)
            cursor.execute('''INSERT INTO files (path, ctime, mtime, hash) VALUES (?,?,?,?)''',
                           (str(file_path), str(os.path.getctime(file_path)), str(os.path.getmtime(file_path)), hash))
            db.commit()
            files_hashes[file_path] = hash

    db.commit()
    db.close()


    for file_hash in files_hashes:
        sys.stdout.write("%s  %s\n" % (files_hashes[file_hash], file_hash))


