#!/bin/sh

find "$@" -maxdepth 1 -mindepth 1 \( -type f -o -type l \) -print0 |
xargs -r0 du -b --max-depth 0 |
sort -k1,1n |
grep -v "^0" |
while read size file; do
    printf "%'d\t\t%s\n" $size $file
done
